
import java.awt.Color;
import java.awt.event.WindowListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author joselo09111
 */
public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstName = new javax.swing.JTextField();
        firstNameLbl = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        lastNameLbl = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        createAccountBtn = new javax.swing.JButton();
        faceRegisteredCheckBox = new javax.swing.JCheckBox();
        registerFaceBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstNameLbl.setText("First Name");

        lastNameLbl.setText("Last Name");

        emailLbl.setText("Email/Username");

        passwordLbl.setText("Password");

        createAccountBtn.setText("Create Account");
        createAccountBtn.setEnabled(false);
        createAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBtnActionPerformed(evt);
            }
        });

        faceRegisteredCheckBox.setText("Face Registered");
        faceRegisteredCheckBox.setEnabled(false);

        registerFaceBtn.setText("Register Face");
        registerFaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerFaceBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel5.setText("Registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerFaceBtn)
                            .addComponent(createAccountBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(faceRegisteredCheckBox))
                            .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(passwordLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(lastNameLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(firstNameLbl))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(emailLbl)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firstNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(faceRegisteredCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerFaceBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createAccountBtn)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerFaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFaceBtnActionPerformed
        // TODO add your handling code here:
        new Face().setVisible(true);
        faceRegistered();
    }//GEN-LAST:event_registerFaceBtnActionPerformed

    private void createAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBtnActionPerformed
        // TODO add your handling code here:
        boolean valid = true;
        if(firstName.getText().isEmpty() || lastName.getText().isEmpty() || password.getText().isEmpty() || email.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please fill out all the required form.");
            if(firstName.getText().isEmpty())
            {
            firstNameLbl.setForeground(new Color(255,0,0));
            }
            if(lastName.getText().isEmpty())
            {
            lastNameLbl.setForeground(new Color(255,0,0));
            }
            if(password.getText().isEmpty())
            {
            passwordLbl.setForeground(new Color(255,0,0));
            }
            if(email.getText().isEmpty())
            {
            emailLbl.setForeground(new Color(255,0,0));
            }
            valid = false;
        }else
        {
            if(password.getText().contains(" "))
            {
                JOptionPane.showMessageDialog(null,"The password cannot contain spaces.");
                valid = false;
            }
            if(!email.getText().contains("@") || !email.getText().contains("."))
            {
                JOptionPane.showMessageDialog(null,"Enter a valid email.");
                valid = false;
            }
            if(loginInfo(email.getText(),password.getText()) != -1)
            {
                JOptionPane.showMessageDialog(null,"Username is already taken.");
                valid = false;
            }
        }
        if(valid)
        {
            try
            {
            FileWriter fw = new FileWriter(new File("login.txt"),true);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.newLine();
            bw.write(email.getText()+"  "+password.getText()+"  "+firstName.getText()+" "+lastName.getText());
            bw.close();
            fw.close();
            JOptionPane.showMessageDialog(null,"Account has been created successfully!");
            this.setVisible(false);
            }catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, "Error: Credential evaluator not working.");
            }
        }
    }//GEN-LAST:event_createAccountBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
         
                new RegisterPage().setVisible(true);
            }
        });
    }
    private int loginInfo(String username, String password)
    {
        try
        {
            Scanner sc = new Scanner(new File("login.txt"));
            sc.nextLine();
            String arr[] = new String[]{"","",""};
            int count = -1;
            while(username.equals("") || password.equals("") || !arr[0].equalsIgnoreCase(username))
            {
            arr = sc.nextLine().split(" ");
            arr = fixArrayLogin(arr);
            count++;
            }
            sc.close();
            if(!username.equals("") && !password.equals("") && arr[0].equalsIgnoreCase(username))
            {
                return count;
            }
        }catch(IOException e)
        {
            JOptionPane.showMessageDialog(null,e.toString());
        }catch(Exception e)
        {
            return -1;
        }
        return -1;
    }
        private String[] fixArrayLogin(String[] arr)
    {
        String[] res = new String[]{"","",""};
        int count = 0;
        for(int i = 0; i < arr.length; i++)
        {
            if(!arr[i].isEmpty())
            {
            res[count] += arr[i] + " ";
            if(count < 2)
                {
                count++;
                }
            }
        }
        for(int i = 0; i < 3; i++)
        {
            res[i] = res[i].substring(0, res[i].length()-1);
        }
        return res;
    }
        public void faceRegistered()
        {
            faceRegisteredCheckBox.setSelected(true);
            createAccountBtn.setEnabled(true);
        }

    @Override
    public void setDefaultCloseOperation(int operation) {
        super.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccountBtn;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JCheckBox faceRegisteredCheckBox;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel firstNameLbl;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JTextField password;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JButton registerFaceBtn;
    // End of variables declaration//GEN-END:variables
}
